trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Deploy
  displayName: Deploy Python Application

  jobs:

  - deployment: DeployToAzure

    displayName: Deploy to Azure App Service

    environment: Production

    strategy:

      runOnce:

        deploy:

          steps:

          # Download the artifact published by the build stage
          - download: $(Build.ArtifactStagingDirectory)
            artifact: pythonapp

          # Deploy to Azure Web App
          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App

            inputs:
              azureSubscription: 'Azure subscription 1(9e6cc00a-2a6b-4596-b517-7ab2de7df8ea)'
              appType: 'webAppLinux'
              appName: 'restapiSatya'
              package: '$(Build.ArtifactStagingDirectory)/pythonapp.zip'